language: php
php:
  - 5.6
install:
  - composer install
  - php app/console doctrine:database:create
  - yes | php app/console doctrine:migrations:migrate
  - yes | php app/console doctrine:fixtures:load
  - php app/console student:generate:path
script:
  - ./bin/phpunit -c app/
  - ./bin/phpcs --standard=PSR2 src/
