parameters:
#    levi9_high_load.example.class: Levi9\HighLoadBundle\Example

services:
    levi9_high_load.student:
        class: Levi9\HighLoadBundle\Service\StudentService
        arguments: [@doctrine.orm.entity_manager]