parameters:
#    levi9_high_load.example.class: Levi9\HighLoadBundle\Example

services:
#    levi9_high_load.example:
#        class: %levi9_high_load.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
